apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: winklerit-com-tls
spec:
  secretName: winklerit-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: winklerit.com
  dnsNames:
    - winklerit.com
    - www.winklerit.com
